create table riesgos.eventoriesgo_matriz (id_evento_riesgo int8 not null, id_matriz_riesgo int8 not null)
create table riesgos.tbl_archivo (arch_id  bigserial not null, arch_base64 bytea, arch_date_time_create timestamp, arch_delete boolean, evento_id int8, arch_nombre_archivo varchar(500), arch_size int8, arch_tipo text, arch_date_time_update timestamp, primary key (arch_id))
create table riesgos.tbl_evento_riesgo (eve_id  bigserial not null, eve_cobertura_seguro boolean, eve_codigo varchar(20), eve_codigo_inicial text, eve_comercio_afectado boolean, eve_date_time_create timestamp, eve_delete boolean, eve_descripcion text, eve_descripcion_completa text, eve_descripcion_estado text, eve_detalle_estado text, eve_detalle_evento_critico text, eve_detalle_plan text, eve_entidad_afectada boolean, eve_estado_evento varchar(30), eve_estado_plan varchar(200), eve_estado_registro varchar(30), eve_estado_reportado varchar(50), eve_evento_critico varchar(500), eve_fecha_contable date, eve_fecha_desc date, eve_fecha_desc_aux int4, eve_fecha_fin date, eve_fecha_fin_plan date, eve_fecha_ini date, eve_gasto_asociado float4, eve_hora_desc time, eve_hora_fin time, eve_hora_ini time, eve_id_area_correlativo int4, eve_linea_negocio varchar(500), eve_monto_perdida float4, eve_monto_recuperado float4, eve_monto_recuperado_seguro float4, eve_otros text, eve_perdida_mercado float4, eve_responsable_elaborador text, eve_tasa_cambio_id varchar(5), eve_tipo_evento varchar(10), eve_trimestre varchar(50), eve_date_time_update timestamp, des_usuario_id int4, eve_agencia_id int8, eve_area_id int8, eve_area_responsable_id int8, eve_canal_asfi_id int8, eve_cargo_id int8, eve_cargo_reponsable_id int8, eve_ciudad_id int8, eve_clase_evento_id int8, eve_cuenta_contable_id int8, eve_cumplimiento_id int8, eve_desc_servicio_id int8, eve_efecto_perdida_id int8, eve_entidad_id int8, eve_estrategico_id int8, eve_factor_riesgo_id int8, eve_fraude_id int8, eve_fuente_inf_id int8, eve_gobierno_id int8, eve_impacto_id int8, eve_legal_id int8, eve_linea_asfi_id int8, eve_liquidez_id int8, eve_moneda_id int8, eve_ope_pro_ser_id int8, eve_operacion_id int8, eve_operativo_id int8, eve_poliza_seguro_id int8, eve_procedimiento_id int8, eve_proceso_id int8, eve_recuperacion_activo_id int8, eve_reputacional_id int8, eve_seguridad_id int8, eve_sub_evento_id int8, eve_subcategorizacion_id int8, eve_tipo_evento_perdida_id int8, eve_tipo_servicio_id int8, eve_unidad_id int8, primary key (eve_id))
create table riesgos.tbl_matriz_oportunidad (opo_id  bigserial not null, opo_causa text, opo_codigo varchar(20), opo_consecuencia text, opo_control_comentario text, opo_controles text, opo_controles_tiene boolean, opo_date_time_create timestamp, opo_definicion text, opo_delete boolean, opo_estado_registro varchar(30), opo_factor varchar(255), opo_fecha_evaluacion date, opo_id_macro_correlativo int4, opo_planes_accion text, opo_date_time_update timestamp, opo_usuario_id int4, opo_area_id int8, opo_dueno_cargo_id int8, opo_foda_desc_id int8, opo_foda_id int8, opo_fortaleza_id int8, opo_grupo_interes_id int8, opo_impacto_opor_id int8, opo_probabilidad_id int8, opo_procedimiento_id int8, opo_proceso_id int8, opo_responsable_cargo_id int8, opo_unidad_id int8, primary key (opo_id))
create table riesgos.tbl_matriz_riesgo (rie_id  bigserial not null, rie_causa text, rie_codigo varchar(20), rie_consecuencia text, rie_control_comentario text, rie_control_objetivo varchar(100), rie_controles text, rie_controles_tiene boolean, rie_date_time_create timestamp, rie_criterio_impacto text, rie_criterio_probabilidad text, rie_definicion text, rie_delete boolean, rie_efecto_perdida_otro varchar(200), rie_estado_registro varchar(30), rie_evento_materializado boolean, rie_evento_riesgo_id int8, rie_fecha_evaluacion date, rie_id_unidad_correlativo int4, rie_identificado_otro text, rie_impacto_usd float4, rie_monetario boolean, rie_planes_accion text, rie_date_time_update timestamp, rie_usuario_id int4, rie_area_id int8, rie_control_id int8, rie_dueno_cargo_id int8, rie_efecto_perdida_id int8, rie_factor_riesgo_id int8, rie_identificado_id int8, rie_impacto_id int8, rie_perdida_asfi_id int8, rie_probabilidad_id int8, rie_procedimiento_id int8, rie_proceso_id int8, rie_responsable_cargo_id int8, rie_unidad_id int8, primary key (rie_id))
create table riesgos.tbl_observacion (obs_id  bigserial not null, obs_date_time_create timestamp, obs_delete boolean, obs_estado varchar(50), obs_lista_observacion varchar(500), obs_modulo varchar(50), obs_nota varchar(1000), obs_date_time_update timestamp, obs_usuario_id int4, obs_evento_id int8, obs_matriz_oportunidad_id int8, obs_matriz_riesgo_id int8, primary key (obs_id))
create table riesgos.tbl_seguridad (seg_id  bigserial not null, seg_activo_informacion varchar(500), seg_ci_seguimiento varchar(1000), seg_comentario varchar(1000), seg_date_time_create timestamp, seg_delete boolean, seg_descripcion_riesgo varchar(2000), seg_fecha_limite date, seg_fecha_registro date, seg_fecha_solucion date, seg_informe_emitido varchar(1000), seg_ip_url varchar(200), seg_plan_trabajo text, seg_recomendacion varchar(1000), seg_red varchar(200), seg_date_time_update timestamp, seg_usuario_id int4, seg_area_id int8, seg_estado_id int8, seg_nivel_riesgo_id int8, seg_tipo_activo_id int8, primary key (seg_id))
create table riesgos.tbl_tabla_descripcion (des_id  bigserial not null, des_campo_a varchar(2000), des_campo_b varchar(2000), des_campo_c text, des_campo_d text, des_clave varchar(50), des_codigo_asfi varchar(50), des_date_time_create timestamp, des_delete boolean, des_descripcion text, des_nivel2_id int4, des_nivel3_id int4, des_nombre varchar(1500), des_date_time_update timestamp, des_usuario_id int4, des_tabla_id int8, primary key (des_id))
create table riesgos.tbl_tabla_descripcion_matriz_oportunidad (des_id  bigserial not null, des_campo_a varchar(1000), des_campo_b varchar(1000), des_campo_c varchar(1000), des_campo_d varchar(1000), des_date_time_create timestamp, des_delete boolean, des_nivel2_id int4, des_nombre varchar(1000), des_date_time_update timestamp, des_usuario_id int4, des_tabla_id int8, primary key (des_id))
create table riesgos.tbl_tabla_descripcion_matriz_riesgo (des_id  bigserial not null, des_campo_a varchar(1000), des_campo_b varchar(1000), des_campo_c varchar(1000), des_campo_d varchar(1000), des_campo_e float4, des_campo_f float4, des_campo_g varchar(1000), des_date_time_create timestamp, des_delete boolean, des_nombre varchar(1000), des_date_time_update timestamp, des_usuario_id int4, des_tabla_id int8, primary key (des_id))
create table riesgos.tbl_tabla_descripcion_seguridad (des_id  bigserial not null, des_date_time_create timestamp, des_delete boolean, des_nombre varchar(1000), des_date_time_update timestamp, des_usuario_id int4, des_tabla_id int8, primary key (des_id))
create table riesgos.tbl_tabla_lista (lis_id  bigserial not null, lis_date_time_create timestamp, lis_delete boolean, lis_nivel2 int4, lis_nivel3 int4, lis_nombre_tabla varchar(100), lis_date_time_update timestamp, lis_usuario_id int4, primary key (lis_id))
create table riesgos.tbl_tabla_lista_matriz_oportunidad (lis_id  bigserial not null, lis_date_time_create timestamp, lis_delete boolean, lis_nivel2 int4, lis_nombre_tabla varchar(100), lis_date_time_update timestamp, lis_usuario_id int4, primary key (lis_id))
create table riesgos.tbl_tabla_lista_matriz_riesgo (lis_id  bigserial not null, lis_date_time_create timestamp, lis_delete boolean, lis_nombre_tabla varchar(100), lis_date_time_update timestamp, lis_usuario_id int4, primary key (lis_id))
create table riesgos.tbl_tabla_lista_seguridad (lis_id  bigserial not null, lis_date_time_create timestamp, lis_delete boolean, lis_nombre_tabla varchar(100), lis_date_time_update timestamp, lis_usuario_id int4, primary key (lis_id))
alter table riesgos.eventoriesgo_matriz add constraint FKrpch9xmvxtpembv2rg0se0wpa foreign key (id_matriz_riesgo) references riesgos.tbl_matriz_riesgo
alter table riesgos.eventoriesgo_matriz add constraint FKs532mtleoyt1k6d8wqqlk1jff foreign key (id_evento_riesgo) references riesgos.tbl_evento_riesgo
alter table riesgos.tbl_archivo add constraint FK85vy43qk8ds9o2euvhe8erxlh foreign key (evento_id) references riesgos.tbl_evento_riesgo
alter table riesgos.tbl_evento_riesgo add constraint FKj9i28e53cl0orvor2k1et3lrx foreign key (eve_agencia_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKsgk3rftla9x7jdwlu5m3xwx3i foreign key (eve_area_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKogms87rj4rqeq1ecn3vhst32l foreign key (eve_area_responsable_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKr6lnb23bvy879b02cwjmw1i7e foreign key (eve_canal_asfi_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKaq1asf6ta57w3e97xmua2b6le foreign key (eve_cargo_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKro4lb4lqmlpt403yg5s6f7gfp foreign key (eve_cargo_reponsable_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FK42fo3thtayg542pjsbo8hbs1h foreign key (eve_ciudad_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKj6b1ai65b9v731s45vofwvwix foreign key (eve_clase_evento_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKddk7uw962vhjipsws5egetcd7 foreign key (eve_cuenta_contable_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKr0s1myad2ve9cnewtuve7aboa foreign key (eve_cumplimiento_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FK9bb4sykdjrydstygcu13i8bvh foreign key (eve_desc_servicio_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKdsw3ejwlmne85pi6li2b9b34g foreign key (eve_efecto_perdida_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FK6x2bwi53333cf4ys60vydm02c foreign key (eve_entidad_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKsikfi91c08ndv9tpkh7kfi6o1 foreign key (eve_estrategico_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKbfy7c6dcnv6u81sofkr1ijq8d foreign key (eve_factor_riesgo_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKnwm7t6nsd07agt4v0qa07sghm foreign key (eve_fraude_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKcadep4ca9y5wa77mmv66r13me foreign key (eve_fuente_inf_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FK7growi0ieni1vlmoosi0psg8f foreign key (eve_gobierno_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKb5vc3rhe4d8qkn6ym1affbjhe foreign key (eve_impacto_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKa3jy5sbf3hnqry1tae1in1ro9 foreign key (eve_legal_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKgxpobfn6k4vwqsukvwvifrjnr foreign key (eve_linea_asfi_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FK4pcgjluvseluj1tvtibp9ikf8 foreign key (eve_liquidez_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKeaf59xkm4dwm6fqpx6uu6kyo6 foreign key (eve_moneda_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKdcp92wmtmoboqu28u32rl8vig foreign key (eve_ope_pro_ser_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FK12w0goi9gtmw35g6k07nqmaxt foreign key (eve_operacion_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKl6ayqnms8fgdh2or9qab30qmd foreign key (eve_operativo_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKfg0onvx0wqodyr9te715asf8q foreign key (eve_poliza_seguro_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKfyu6nkn5y6kmd5mkqa2xrxon4 foreign key (eve_procedimiento_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKpsl268e3c8g3y9jjujjq0766f foreign key (eve_proceso_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKtqw1xookc76p3y1ep1li254g8 foreign key (eve_recuperacion_activo_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKhtv53t6a16i78byqdscb8p0hw foreign key (eve_reputacional_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FK16nno652f0lakx6qsndg2a1i8 foreign key (eve_seguridad_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKx5kn11pg4ccxt8s9a8comjim foreign key (eve_sub_evento_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKkli2cey2x1bvpi7pgxa49kyen foreign key (eve_subcategorizacion_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKfxlah17g0x076x37cipw0my5j foreign key (eve_tipo_evento_perdida_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FK84s1katn3qc9ormvjag3ywoyt foreign key (eve_tipo_servicio_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_evento_riesgo add constraint FKd936bomogb9tyjmjdttjl3xwj foreign key (eve_unidad_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_oportunidad add constraint FK2f0i0mskcvidijk6e87o1svnt foreign key (opo_area_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_oportunidad add constraint FK1sif95enpcpr8y1ehfwgitgww foreign key (opo_dueno_cargo_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_oportunidad add constraint FK4ubq5wmw6r5f3cfrj0qnvmtg3 foreign key (opo_foda_desc_id) references riesgos.tbl_tabla_descripcion_matriz_oportunidad
alter table riesgos.tbl_matriz_oportunidad add constraint FKidm8jrj82sahtxjdtfumw3py3 foreign key (opo_foda_id) references riesgos.tbl_tabla_descripcion_matriz_oportunidad
alter table riesgos.tbl_matriz_oportunidad add constraint FKmmoi0ww81xr8vfknacc6r3496 foreign key (opo_fortaleza_id) references riesgos.tbl_tabla_descripcion_matriz_oportunidad
alter table riesgos.tbl_matriz_oportunidad add constraint FKj9jvw67ltclm3fxgjn88qscx4 foreign key (opo_grupo_interes_id) references riesgos.tbl_tabla_descripcion_matriz_oportunidad
alter table riesgos.tbl_matriz_oportunidad add constraint FK6iuhiojnubmt38b3v1522x05m foreign key (opo_impacto_opor_id) references riesgos.tbl_tabla_descripcion_matriz_oportunidad
alter table riesgos.tbl_matriz_oportunidad add constraint FKgb5girltaqcchc4pcoc0is4bc foreign key (opo_probabilidad_id) references riesgos.tbl_tabla_descripcion_matriz_riesgo
alter table riesgos.tbl_matriz_oportunidad add constraint FK5egsp3dsywyibse5ixupf0g7l foreign key (opo_procedimiento_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_oportunidad add constraint FKryevfqcww1lx795m853mvkqq2 foreign key (opo_proceso_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_oportunidad add constraint FK6hd8qa7e9p3uvl559lmalared foreign key (opo_responsable_cargo_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_oportunidad add constraint FKgr3ny7q7kn8h9s4863t7fxws7 foreign key (opo_unidad_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_riesgo add constraint FKnjjldgqewxa0m0ks4i6gyc5qo foreign key (rie_area_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_riesgo add constraint FKp81eilrr2lpk0mq9ocsxdaq32 foreign key (rie_control_id) references riesgos.tbl_tabla_descripcion_matriz_riesgo
alter table riesgos.tbl_matriz_riesgo add constraint FK1ujr48qlf0gd7s8egpnncv3fb foreign key (rie_dueno_cargo_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_riesgo add constraint FKhcfiur4a8vls3r6ermw1a660y foreign key (rie_efecto_perdida_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_riesgo add constraint FK4w54y9uh4dlt6df1x2m8n163b foreign key (rie_factor_riesgo_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_riesgo add constraint FKt0q7i2d061qvo72fb4xrdkegt foreign key (rie_identificado_id) references riesgos.tbl_tabla_descripcion_matriz_riesgo
alter table riesgos.tbl_matriz_riesgo add constraint FK64y80n1mwnifdnqupggw7v490 foreign key (rie_impacto_id) references riesgos.tbl_tabla_descripcion_matriz_riesgo
alter table riesgos.tbl_matriz_riesgo add constraint FKelse5n5bkf3i5il4onwml1ouh foreign key (rie_perdida_asfi_id) references riesgos.tbl_tabla_descripcion_matriz_riesgo
alter table riesgos.tbl_matriz_riesgo add constraint FKidt5n7bdp4go75dktprp5mfow foreign key (rie_probabilidad_id) references riesgos.tbl_tabla_descripcion_matriz_riesgo
alter table riesgos.tbl_matriz_riesgo add constraint FK63469q9wth99y4jwb63s1wt90 foreign key (rie_procedimiento_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_riesgo add constraint FKharoo3c6fpov3b6kafdg3dd1k foreign key (rie_proceso_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_riesgo add constraint FK4x34kbk69bebc3l7ym2s5tkam foreign key (rie_responsable_cargo_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_matriz_riesgo add constraint FK1ut6pluqghfpd2stv5igky9lp foreign key (rie_unidad_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_observacion add constraint FKdnnvfyulebv8qahp5ef33t5ce foreign key (obs_evento_id) references riesgos.tbl_evento_riesgo
alter table riesgos.tbl_observacion add constraint FKakdglyt4njplc0rglx37fh96x foreign key (obs_matriz_oportunidad_id) references riesgos.tbl_matriz_oportunidad
alter table riesgos.tbl_observacion add constraint FK7qth4ovpk9gpxk77bd3vbswou foreign key (obs_matriz_riesgo_id) references riesgos.tbl_matriz_riesgo
alter table riesgos.tbl_seguridad add constraint FK5dxus83dnqalidtadxbly0e15 foreign key (seg_area_id) references riesgos.tbl_tabla_descripcion
alter table riesgos.tbl_seguridad add constraint FK9fmlgs6dhqc0tefltrllot39y foreign key (seg_estado_id) references riesgos.tbl_tabla_descripcion_seguridad
alter table riesgos.tbl_seguridad add constraint FK335ruhco3sy31u2e9e9u0lpeh foreign key (seg_nivel_riesgo_id) references riesgos.tbl_tabla_descripcion_matriz_riesgo
alter table riesgos.tbl_seguridad add constraint FK6uai154rbvcx4onra117jhndq foreign key (seg_tipo_activo_id) references riesgos.tbl_tabla_descripcion_seguridad
alter table riesgos.tbl_tabla_descripcion add constraint FK1e9cn10loq6vfibruy5h98yd foreign key (des_tabla_id) references riesgos.tbl_tabla_lista
alter table riesgos.tbl_tabla_descripcion_matriz_oportunidad add constraint FKse9mdydrut2d7tmro5g0adgbh foreign key (des_tabla_id) references riesgos.tbl_tabla_lista_matriz_oportunidad
alter table riesgos.tbl_tabla_descripcion_matriz_riesgo add constraint FK2b6o330bhge9dug9sqowvon7m foreign key (des_tabla_id) references riesgos.tbl_tabla_lista_matriz_riesgo
alter table riesgos.tbl_tabla_descripcion_seguridad add constraint FKryajw0hpjk0h6oucvs4iocqdg foreign key (des_tabla_id) references riesgos.tbl_tabla_lista_seguridad
